function plan_full = call_day_ahead_planner_by_mode( ...
    P_load_48h, ...
    P_pv_48h, ...
    Prices_48h, ...
    pars, ...
    tariff, ...
    dt_h, ...
    contract_state, ...
    target_step_min, ...
    dispatch_cfg)
% CALL_DAY_AHEAD_PLANNER_BY_MODE
%
% Kozponti planner-dispatcher.
%
% Feladata:
%   - topology szerint valaszt: DC vagy AC,
%   - objective mode szerint valaszt:
%       "peak_only"
%       "energy_only"
%       "combined"
%
% Igy a full horizon es a contract search ugyanazt a planner-valasztasi
% logikat hasznalja.

    coupling = lower(string(dispatch_cfg.bessCoupling));
    objectiveMode = lower(string(dispatch_cfg.objectiveMode));

    switch coupling

        case "dc"

            switch objectiveMode

                case "peak_only"

                    plan_full = ems_day_ahead_planner_milp_peak_dc( ...
                        P_load_48h, ...
                        P_pv_48h, ...
                        Prices_48h, ...
                        pars, ...
                        tariff, ...
                        dt_h, ...
                        contract_state, ...
                        target_step_min);

                case "energy_only"

                    plan_full = ems_day_ahead_planner_milp_energy_dc( ...
                        P_load_48h, ...
                        P_pv_48h, ...
                        Prices_48h, ...
                        pars, ...
                        tariff, ...
                        dt_h, ...
                        contract_state, ...
                        target_step_min, ...
                        dispatch_cfg);

                case "combined"

                    plan_full = ems_day_ahead_planner_milp_contract( ...
                        P_load_48h, ...
                        P_pv_48h, ...
                        Prices_48h, ...
                        pars, ...
                        tariff, ...
                        dt_h, ...
                        contract_state, ...
                        target_step_min);

                otherwise

                    error('Unknown dispatch objectiveMode for DC planner: %s', objectiveMode);
            end

        case "ac"

            switch objectiveMode

                case "peak_only"

                    plan_full = ems_day_ahead_planner_milp_peak_ac( ...
                        P_load_48h, ...
                        P_pv_48h, ...
                        Prices_48h, ...
                        pars, ...
                        tariff, ...
                        dt_h, ...
                        contract_state, ...
                        target_step_min);

                case "energy_only"

                    plan_full = ems_day_ahead_planner_milp_energy_ac( ...
                        P_load_48h, ...
                        P_pv_48h, ...
                        Prices_48h, ...
                        pars, ...
                        tariff, ...
                        dt_h, ...
                        contract_state, ...
                        target_step_min, ...
                        dispatch_cfg);

                case "combined"

                    plan_full = ems_day_ahead_planner_milp_contract_ac( ...
                        P_load_48h, ...
                        P_pv_48h, ...
                        Prices_48h, ...
                        pars, ...
                        tariff, ...
                        dt_h, ...
                        contract_state, ...
                        target_step_min);

                otherwise

                    error('Unknown dispatch objectiveMode for AC planner: %s', objectiveMode);
            end

        otherwise

            error('Unknown bessCoupling mode: %s. Use "dc" or "ac".', coupling);
    end
end