function cfg = create_configurations(basePath)
% CREATE_CONFIGURATIONS
%
% Kozponti konfiguracio ipari grid-connected PV+BESS feladathoz:
%   - peak shaving
%   - energia arbitrazs
%   - onfogyasztas
%   - lekotott teljesitmeny optimalizalas

    cfg = struct();

    % =====================================================================
    % 1) System
    % =====================================================================
    cfg.system.bessCoupling = "dc";
    cfg.system.useCase = "industrial_peak_shaving_arbitrage";

    cfg.profiling.enabled = true;

    cfg.dispatch.objectiveMode = "energy_only";
    cfg.dispatch.energyOnlyGridCap_kW = 1000;
    cfg.dispatch.peakOnlyDisableEnergyCost = true;
    cfg.dispatch.noBessContract_kW = 700;

    cfg.grid.allowExport = true;
    cfg.targetStepMin = 15;
    cfg.aggregationMethod = "mean";

    % =====================================================================
    % 2) Paths
    % =====================================================================
    cfg.paths.base = basePath;
    cfg.paths.results = fullfile(basePath, 'results');
    cfg.paths.figures = fullfile(cfg.paths.results, 'figures');

    if ~exist(cfg.paths.results, 'dir')
        mkdir(cfg.paths.results);
    end

    if ~exist(cfg.paths.figures, 'dir')
        mkdir(cfg.paths.figures);
    end

    % =====================================================================
    % 3) Simulation horizon
    % =====================================================================
    cfg.analysis.simYears = 6;
    cfg.loadScale = 1.0;

    % =====================================================================
    % 4) Fixed PV + inverter system
    % =====================================================================
    cfg.dc.P_inv_kW = 550;

    cfg.pvA.tiltX = 11;
    cfg.pvA.tiltZ = [95, 275];
    cfg.pvA.P_dc_kWp = [274, 274];

    cfg.pvB.tiltX = 11;
    cfg.pvB.tiltZ = [70, 250];
    cfg.pvB.P_dc_kWp = [100.5, 100.5];

    cfg.pv.modulePower_kWp = 0.325;

    cfg.pv.P_total_dc_kWp = ...
        sum(cfg.pvA.P_dc_kWp) + sum(cfg.pvB.P_dc_kWp);

    % =====================================================================
    % 5) Power converter efficiency models
    % =====================================================================
    % A szimulacioban harom teljesitmenyatalakito eszkoz szerepel:
    %   1) central_inv: kozponti PV inverter / kozos DC/AC inverter
    %   2) dcdc       : DC-csatolt BESS ag DC/DC konvertere
    %   3) pcsb       : AC-csatolt BESS PCS invertere
    % Mindegyik ugyanazt a teljesitmenyfuggo hatasfok-elvet hasznalja.

    cfg.converter = struct();

    cfg.converter.central_inv = struct();
    cfg.converter.central_inv.eta_nom = 0.985;
    cfg.converter.central_inv.load_points = [0.00 0.02 0.05 0.10 0.20 0.50 1.00];
    cfg.converter.central_inv.eta_points  = [0.00 0.90 0.955 0.975 0.983 0.987 0.985];

    cfg.converter.dcdc = struct();
    cfg.converter.dcdc.eta_nom = 0.985;
    cfg.converter.dcdc.load_points = [0.00 0.02 0.05 0.10 0.20 0.50 1.00];
    cfg.converter.dcdc.eta_points  = [0.00 0.90 0.950 0.970 0.982 0.987 0.985];

    cfg.converter.pcsb = struct();
    cfg.converter.pcsb.eta_nom = 0.980;
    cfg.converter.pcsb.load_points = [0.00 0.02 0.05 0.10 0.20 0.50 1.00];
    cfg.converter.pcsb.eta_points  = [0.00 0.88 0.930 0.955 0.972 0.982 0.980];

    % Backward compatibility aliasok.
    cfg.dc.central_inv_eta_nom = cfg.converter.central_inv.eta_nom;
    cfg.dc.central_inv_eff_load_points = cfg.converter.central_inv.load_points;
    cfg.dc.central_inv_eff_eta_points  = cfg.converter.central_inv.eta_points;

    cfg.bess.dcdc_eta_nom = cfg.converter.dcdc.eta_nom;
    cfg.bess.dcdc_eff_load_points = cfg.converter.dcdc.load_points;
    cfg.bess.dcdc_eff_eta_points  = cfg.converter.dcdc.eta_points;

    cfg.bess.pcs_eta_nom = cfg.converter.pcsb.eta_nom;
    cfg.bess.pcs_eff_load_points = cfg.converter.pcsb.load_points;
    cfg.bess.pcs_eff_eta_points  = cfg.converter.pcsb.eta_points;

    cfg.dc.inv_eta = cfg.converter.central_inv.eta_nom;

    % =====================================================================
    % 6) BESS candidate space
    % =====================================================================
    cfg.candidates.BESS_PV_ratio_vec = 0:0.5:6;
    cfg.candidates.bessDuration_h = 2;

    cfg.candidates.designFields = { ...
        'BESS_PV_ratio', ...
        'P_PV_A_kW', ...
        'P_PV_B_kW', ...
        'P_PV_kW', ...
        'P_inv_kW', ...
        'E_BESS_kWh', ...
        'P_BESS_kW'};

    % =====================================================================
    % 7) Contract search
    % =====================================================================
    cfg.contractSearch.coarse_step_kW = 25;
    cfg.contractSearch.fine_step_kW = 10;
    cfg.contractSearch.validation_offsets_kW = [-20 -10 0 10 20];

    cfg.contractSearch.min_kW = 400;
    cfg.contractSearch.max_kW = 1200;

    cfg.contractSearch.proxy.n_typical = 5;
    cfg.contractSearch.proxy.n_extreme = 2;

    cfg.contractSearch.validation.n_clusters = 5;
    cfg.contractSearch.validation.n_validation_days_total = 20;
    cfg.contractSearch.validation.n_extreme_force = 4;

    % =====================================================================
    % 8) Dispatch / economics
    % =====================================================================
    cfg.dispatch.degradation_cost_per_kWh = 5.0;
    cfg.dispatch.P_grid_hard_cap_kW = 700;
    cfg.dispatch.P_contract_safety_factor = 0.90;

    % =====================================================================
    % 9) Cost parameters
    % =====================================================================
    cfg.cost.eur_to_huf = 350;

    cfg.cost.pv_huf_per_kWp = 300000;
    cfg.cost.bess_huf_per_kWh = cfg.cost.eur_to_huf * 220;
    cfg.cost.bess_power_huf_per_kW = 0;
    cfg.cost.inverter_huf_per_kW = 40000;

    cfg.cost.project_lifetime_years = 20;
    cfg.cost.pv_lifetime_years = 25;
    cfg.cost.inverter_lifetime_years = 15;
    cfg.cost.discount_rate = 0.06;

    cfg.cost.pv_opex_frac_per_year = 0.015;
    cfg.cost.bess_opex_frac_per_year = 0.020;
    cfg.cost.inverter_opex_frac_per_year = 0.010;

    cfg.cost.grid_import_huf_per_kWh = 75;
    cfg.cost.grid_export_huf_per_kWh = 0;

    % =====================================================================
    % 10) Simulation / storage
    % =====================================================================
    cfg.sim.saveAfterEachCandidate = true;
    cfg.sim.verbose = true;
    cfg.sim.strictMetricSources = true;

    % =====================================================================
    % 11) Diagnostics
    % =====================================================================
    cfg.diagnostics = struct();
    cfg.diagnostics.enabled = false;
    cfg.diagnostics.testMode = cfg.diagnostics.enabled;
    cfg.diagnostics.candidateIndex = 11;

    if cfg.diagnostics.enabled
        cfg.diagnostics.storeCandidateDetail = false;
        cfg.diagnostics.storePlannerDebug = true;
        cfg.diagnostics.makePlots = true;
        cfg.diagnostics.saveFigures = true;
        cfg.diagnostics.closeFiguresAfterSave = false;
        cfg.diagnostics.printPlannerDebug = false;
        cfg.diagnostics.maxPrintedDebugDays = 15;
        cfg.diagnostics.makePlannerExecutionDebugPlot = true;
        cfg.diagnostics.plotDispatchDiagnosticsForBaseline = false;
        cfg.diagnostics.makeDispatchDiagnosticPlots = true;
    else
        cfg.diagnostics.storeCandidateDetail = false;
        cfg.diagnostics.storePlannerDebug = false;
        cfg.diagnostics.makePlots = false;
        cfg.diagnostics.saveFigures = false;
        cfg.diagnostics.closeFiguresAfterSave = false;
        cfg.diagnostics.printPlannerDebug = false;
        cfg.diagnostics.maxPrintedDebugDays = 15;
        cfg.diagnostics.makePlannerExecutionDebugPlot = false;
        cfg.diagnostics.plotDispatchDiagnosticsForBaseline = false;
        cfg.diagnostics.makeDispatchDiagnosticPlots = false;
    end

    cfg.diagnostics.runEvaluation = true;
    cfg.diagnostics.outputFolder = fullfile(cfg.paths.results, 'diagnostics');

    if ~exist(cfg.diagnostics.outputFolder, 'dir')
        mkdir(cfg.diagnostics.outputFolder);
    end

    % =====================================================================
    % 12) Detail / selected day plotting configuration
    % =====================================================================
    cfg.detail = struct();
    cfg.detail.max_representative_plots = 8;
    cfg.detail.max_overrun_days = 8;
    cfg.detail.overrun_tolerance_kW = 1e-6;

    % =====================================================================
    % 13) Evaluation
    % =====================================================================
    cfg.evaluation = struct();

    if cfg.system.bessCoupling == "dc"
        cfg.evaluation.resultFileName = "results_dccoupled.mat";
    else
        cfg.evaluation.resultFileName = "results_accoupled.mat";
    end

    cfg.evaluation.simYears = cfg.analysis.simYears;
    cfg.evaluation.selectionMode = "minObjectiveCost";

    % =====================================================================
    % 14) OUTPUT METRICS - SCALAR
    % =====================================================================
    cfg.output.scalarMetrics = struct( ...
        'name', { ...
            'loadEnergy_kWh', ...
            'pvEnergyAvailable_kWh', ...
            'gridImport_kWh', ...
            'gridImportNoBess_kWh', ...
            'bessCharge_kWh', ...
            'bessDischarge_kWh', ...
            'bessThroughput_kWh', ...
            'curtailment_kWh', ...
            'energyCost_HUF', ...
            'energyCostNoBess_HUF', ...
            'degradationCost_HUF', ...
            'overrunCost_HUF', ...
            'contractCost_HUF', ...
            'objectiveCost_HUF', ...
            'maxLoadPeak_kW', ...
            'maxPVPeak_kW', ...
            'maxGridImportPeak_kW', ...
            'maxGridImportNoBessPeak_kW', ...
            'maxBessChargePeak_kW', ...
            'maxBessDischargePeak_kW' ...
        }, ...
        'source', { ...
            'P_load_kW', ...
            'P_pv_available_kW', ...
            'P_grid_import_kW', ...
            'P_grid_import_no_bess_kW', ...
            'P_bess_charge_kW', ...
            'P_bess_discharge_kW', ...
            'P_bess_throughput_kW', ...
            'P_curtailment_kW', ...
            'C_energy_step_HUF', ...
            'C_energy_no_bess_step_HUF', ...
            'C_degradation_step_HUF', ...
            'C_overrun_step_HUF', ...
            'C_contract_step_HUF', ...
            'C_objective_step_HUF', ...
            'P_load_kW', ...
            'P_pv_available_kW', ...
            'P_grid_import_kW', ...
            'P_grid_import_no_bess_kW', ...
            'P_bess_charge_kW', ...
            'P_bess_discharge_kW' ...
        }, ...
        'mode', { ...
            'energySum', ...
            'energySum', ...
            'energySum', ...
            'energySum', ...
            'energySum', ...
            'energySum', ...
            'energySum', ...
            'energySum', ...
            'sum', ...
            'sum', ...
            'sum', ...
            'sum', ...
            'sum', ...
            'sum', ...
            'max', ...
            'max', ...
            'max', ...
            'max', ...
            'max', ...
            'max' ...
        });

    % =====================================================================
    % 15) OUTPUT METRICS - SUMMARY
    % =====================================================================
    cfg.output.summaryMetrics = struct( ...
        'name', { ...
            'bestContract_kW', ...
            'finalSoC', ...
            'finalSoH', ...
            'contractSearchRuntime_s', ...
            'fullHorizonRuntime_s' ...
        }, ...
        'source', { ...
            'bestContract_kW', ...
            'finalSoC', ...
            'finalSoH', ...
            'contractSearchRuntime_s', ...
            'fullHorizonRuntime_s' ...
        });

    % =====================================================================
    % 16) OUTPUT METRICS - PROFILE
    % =====================================================================
    cfg.output.profileMetrics = struct( ...
        'name', { ...
            'meanLoad_kW', ...
            'peakLoad_kW', ...
            'meanPvAvailable_kW', ...
            'peakPvAvailable_kW', ...
            'meanGridImport_kW', ...
            'peakGridImport_kW', ...
            'meanGridImportNoBess_kW', ...
            'peakGridImportNoBess_kW', ...
            'meanBessCharge_kW', ...
            'peakBessCharge_kW', ...
            'meanBessDischarge_kW', ...
            'peakBessDischarge_kW', ...
            'meanCurtailment_kW', ...
            'peakCurtailment_kW', ...
            'meanSoC', ...
            'minSoC', ...
            'maxSoC' ...
        }, ...
        'source', { ...
            'P_load_kW', ...
            'P_load_kW', ...
            'P_pv_available_kW', ...
            'P_pv_available_kW', ...
            'P_grid_import_kW', ...
            'P_grid_import_kW', ...
            'P_grid_import_no_bess_kW', ...
            'P_grid_import_no_bess_kW', ...
            'P_bess_charge_kW', ...
            'P_bess_charge_kW', ...
            'P_bess_discharge_kW', ...
            'P_bess_discharge_kW', ...
            'P_curtailment_kW', ...
            'P_curtailment_kW', ...
            'SoC', ...
            'SoC', ...
            'SoC' ...
        }, ...
        'mode', { ...
            'meanProfile', ...
            'maxProfile', ...
            'meanProfile', ...
            'maxProfile', ...
            'meanProfile', ...
            'maxProfile', ...
            'meanProfile', ...
            'maxProfile', ...
            'meanProfile', ...
            'maxProfile', ...
            'meanProfile', ...
            'maxProfile', ...
            'meanProfile', ...
            'maxProfile', ...
            'meanProfile', ...
            'minProfile', ...
            'maxProfile' ...
        });

    % =====================================================================
    % 17) OUTPUT METRICS - DERIVED
    % =====================================================================
    cfg.output.derivedMetrics = struct( ...
        'name', { ...
            'gridImportReduction_kWh', ...
            'gridImportReduction_pct', ...
            'peakReduction_kW', ...
            'peakReduction_pct', ...
            'energyCostSaving_HUF', ...
            'equivalentCycles', ...
            'specificObjectiveCost_HUF_per_kWhLoad' ...
        }, ...
        'operation', { ...
            'difference', ...
            'percentReduction', ...
            'difference', ...
            'percentReduction', ...
            'difference', ...
            'equivalentCycles', ...
            'ratio' ...
        }, ...
        'inputs', { ...
            {'gridImportNoBess_kWh', 'gridImport_kWh'}, ...
            {'gridImportNoBess_kWh', 'gridImport_kWh'}, ...
            {'maxGridImportNoBessPeak_kW', 'maxGridImportPeak_kW'}, ...
            {'maxGridImportNoBessPeak_kW', 'maxGridImportPeak_kW'}, ...
            {'energyCostNoBess_HUF', 'energyCost_HUF'}, ...
            {'bessThroughput_kWh', 'E_BESS_kWh'}, ...
            {'objectiveCost_HUF', 'loadEnergy_kWh'} ...
        });
end
