function cfg = create_configurations(basePath)
% CREATE_CONFIGURATIONS
%
% Kozponti konfiguracio ipari grid-connected PV+BESS feladathoz:
%   - peak shaving
%   - energia arbitrazs
%   - onfogyasztas
%   - lekotott teljesitmeny optimalizalas

    cfg = struct();

    % =====================================================================
    % 1) System
    % =====================================================================
    cfg.system.bessCoupling = "dc";
    cfg.system.useCase = "industrial_peak_shaving_arbitrage";

    cfg.profiling.enabled = true;

    
    cfg.dispatch.objectiveMode = "combined";
    
    cfg.dispatch.peakOnlyDisableEnergyCost = true;
    cfg.dispatch.noBessContract_kW = 700;
    cfg.dispatch.energyOnlyGridCap_kW = 1000;
    %Alternative milp control logic with faster operation
    cfg.dispatch.useFastDayAheadMILP = false;
    cfg.dispatch.fastMilpSimultaneousPowerTolerance_kW = 1e-5;

    cfg.dispatch.plannerEtaSohGain = 0.50;
    cfg.dispatch.plannerEtaMinFactor = 0.90;


    cfg.grid.allowExport = true;
    cfg.targetStepMin = 15;
    cfg.aggregationMethod = "mean";

    % =====================================================================
    % 2) Paths
    % =====================================================================
    cfg.paths.base = basePath;
    cfg.paths.results = fullfile(basePath, 'results');
    cfg.paths.figures = fullfile(cfg.paths.results, 'figures');

    if ~exist(cfg.paths.results, 'dir')
        mkdir(cfg.paths.results);
    end

    if ~exist(cfg.paths.figures, 'dir')
        mkdir(cfg.paths.figures);
    end

    % =====================================================================
    % 3) Simulation horizon
    % =====================================================================
    cfg.analysis.simYears = 6;
    cfg.loadScale = 1.0;

    % =====================================================================
    % 4) Fixed PV + inverter system
    % =====================================================================
    cfg.dc.P_inv_kW = 550;

    cfg.pvA.tiltX = 11;
    cfg.pvA.tiltZ = [95, 275];
    cfg.pvA.P_dc_kWp = [274, 274];

    cfg.pvB.tiltX = 11;
    cfg.pvB.tiltZ = [70, 250];
    cfg.pvB.P_dc_kWp = [100.5, 100.5];

    cfg.pv.modulePower_kWp = 0.325;

    cfg.pv.P_total_dc_kWp = ...
        sum(cfg.pvA.P_dc_kWp) + sum(cfg.pvB.P_dc_kWp);

    % =====================================================================
    % 5) Power converter efficiency models
    % =====================================================================
    % A szimulacioban harom teljesitmenyatalakito eszkoz szerepel:
    %   1) central_inv: kozponti PV inverter / kozos DC/AC inverter
    %   2) dcdc       : DC-csatolt BESS ag DC/DC konvertere
    %   3) pcsb       : AC-csatolt BESS PCS invertere
    % Mindegyik ugyanazt a teljesitmenyfuggo hatasfok-elvet hasznalja.

    cfg.converter = struct();

    cfg.converter.central_inv = struct();
    cfg.converter.central_inv.eta_nom = 0.985;
    cfg.converter.central_inv.load_points = [0.00 0.02 0.05 0.10 0.20 0.50 1.00];
    % cfg.converter.central_inv.eta_points  = [0.00 0.90 0.955 0.975 0.983 0.987 0.985];
    cfg.converter.central_inv.eta_points  = [0.00 0.89 0.945 0.965 0.973 0.977 0.975];

    cfg.converter.dcdc = struct();
    cfg.converter.dcdc.eta_nom = 0.985;
    cfg.converter.dcdc.load_points = [0.00 0.02 0.05 0.10 0.20 0.50 1.00];
    % cfg.converter.dcdc.eta_points  = [0.00 0.90 0.950 0.970 0.982 0.987 0.985];
    cfg.converter.dcdc.eta_points  = [0.00 0.89 0.94 0.96 0.972 0.977 0.975];

    cfg.converter.pcsb = struct();
    cfg.converter.pcsb.eta_nom = 0.980;
    cfg.converter.pcsb.load_points = [0.00 0.02 0.05 0.10 0.20 0.50 1.00];
    % cfg.converter.pcsb.eta_points  = [0.00 0.88 0.930 0.955 0.972 0.982 0.980];
    cfg.converter.pcsb.eta_points  = [0.00 0.87 0.920 0.945 0.962 0.972 0.970];

    % Backward compatibility aliasok.
    cfg.dc.central_inv_eta_nom = cfg.converter.central_inv.eta_nom;
    cfg.dc.central_inv_eff_load_points = cfg.converter.central_inv.load_points;
    cfg.dc.central_inv_eff_eta_points  = cfg.converter.central_inv.eta_points;

    cfg.bess.dcdc_eta_nom = cfg.converter.dcdc.eta_nom;
    cfg.bess.dcdc_eff_load_points = cfg.converter.dcdc.load_points;
    cfg.bess.dcdc_eff_eta_points  = cfg.converter.dcdc.eta_points;

    cfg.bess.pcs_eta_nom = cfg.converter.pcsb.eta_nom;
    cfg.bess.pcs_eff_load_points = cfg.converter.pcsb.load_points;
    cfg.bess.pcs_eff_eta_points  = cfg.converter.pcsb.eta_points;

    cfg.dc.inv_eta = cfg.converter.central_inv.eta_nom;

    % =====================================================================
    % 6) BESS candidate space
    % =====================================================================
    cfg.candidates.BESS_PV_ratio_vec = 0:0.5:3;
    cfg.candidates.hybrid.BESS_PV_ratio_vec = 0.5:0.5:1.5;
    % cfg.candidates.BESS_PV_ratio_vec = [0 1 2 3];
    cfg.candidates.bessDuration_h = 2;

    cfg.candidates.designFields = { ...
        'BESS_PV_ratio', ...
        'P_PV_A_kW', ...
        'P_PV_B_kW', ...
        'P_PV_kW', ...
        'P_inv_kW', ...
        'E_BESS_kWh', ...
        'P_BESS_kW'};

    % =====================================================================
    % 7) Contract search
    % =====================================================================
    cfg.contractSearch.coarse_step_kW = 25;
    cfg.contractSearch.fine_step_kW = 10;
    cfg.contractSearch.validation_offsets_kW = [-20 -10 0 10 20];

    cfg.contractSearch.min_kW = 400;
    cfg.contractSearch.max_kW = 1200;

    cfg.contractSearch.E_cap_factor = 0.90;

    cfg.contractSearch.proxy.n_typical = 5;
    cfg.contractSearch.proxy.n_extreme = 2;

    cfg.contractSearch.validation.n_clusters = 5;
    cfg.contractSearch.validation.n_validation_days_total = 20;
    cfg.contractSearch.validation.n_extreme_force = 4;

    % =====================================================================
    % 8) Dispatch / economics
    % =====================================================================
    cfg.dispatch.degradation_cost_per_kWh = 5.0;
    cfg.dispatch.P_grid_hard_cap_kW = 700;
    cfg.dispatch.P_contract_safety_factor = 0.90;

    % =====================================================================
    % 9) Cost parameters
    % =====================================================================
    cfg.cost.eur_to_huf = 400;

    cfg.cost.pv_huf_per_kWp = 300000;
    cfg.cost.bess_huf_per_kWh = cfg.cost.eur_to_huf * 220;
    cfg.cost.bess_power_huf_per_kW = 0;
    cfg.cost.inverter_huf_per_kW = 40000;

    cfg.cost.bess_eol_soh_window = 0.2;

    cfg.cost.project_lifetime_years = 20;
    cfg.cost.pv_lifetime_years = 25;
    cfg.cost.inverter_lifetime_years = 15;
    cfg.cost.discount_rate = 0.06;

    cfg.cost.pv_opex_frac_per_year = 0.015;
    cfg.cost.bess_opex_frac_per_year = 0.020;
    cfg.cost.inverter_opex_frac_per_year = 0.010;

    cfg.cost.grid_import_huf_per_kWh = 75;
    cfg.cost.grid_export_huf_per_kWh = 0;

    % =====================================================================
    % 10) Simulation / storage
    % =====================================================================
    cfg.sim.saveAfterEachCandidate = true;
    cfg.sim.verbose = true;
    cfg.sim.strictMetricSources = true;

    % =====================================================================
    % 11) Diagnostics
    % =====================================================================
    cfg.diagnostics = struct();
    cfg.diagnostics.enabled = true;
    cfg.diagnostics.testMode = cfg.diagnostics.enabled;
    cfg.diagnostics.candidateIndex = 3;

    if cfg.diagnostics.enabled
        cfg.diagnostics.storeCandidateDetail = false;
        cfg.diagnostics.storePlannerDebug = true;
        cfg.diagnostics.makePlots = true;
        cfg.diagnostics.saveFigures = true;
        cfg.diagnostics.closeFiguresAfterSave = false;
        cfg.diagnostics.printPlannerDebug = false;
        cfg.diagnostics.maxPrintedDebugDays = 8;
        cfg.diagnostics.makePlannerExecutionDebugPlot = true;
        cfg.diagnostics.plotDispatchDiagnosticsForBaseline = false;
        cfg.diagnostics.makeDispatchDiagnosticPlots = true;
    else
        cfg.diagnostics.storeCandidateDetail = false;
        cfg.diagnostics.storePlannerDebug = false;
        cfg.diagnostics.makePlots = false;
        cfg.diagnostics.saveFigures = false;
        cfg.diagnostics.closeFiguresAfterSave = false;
        cfg.diagnostics.printPlannerDebug = false;
        cfg.diagnostics.maxPrintedDebugDays = 8;
        cfg.diagnostics.makePlannerExecutionDebugPlot = false;
        cfg.diagnostics.plotDispatchDiagnosticsForBaseline = false;
        cfg.diagnostics.makeDispatchDiagnosticPlots = false;
    end

    cfg.diagnostics.runEvaluation = true;
    cfg.diagnostics.outputFolder = fullfile(cfg.paths.results, 'diagnostics');

    if ~exist(cfg.diagnostics.outputFolder, 'dir')
        mkdir(cfg.diagnostics.outputFolder);
    end

    % =====================================================================
    % 12) Detail / selected day plotting configuration
    % =====================================================================
    cfg.detail = struct();
    cfg.detail.max_representative_plots = 4;
    cfg.detail.max_overrun_days = 15;
    cfg.detail.overrun_tolerance_kW = 1e-6;

    % =====================================================================
    % 13) Evaluation
    % =====================================================================
    cfg.evaluation = struct();

    if cfg.system.bessCoupling == "dc"
        cfg.evaluation.resultFileName = "results_dccoupled.mat";
    else
        cfg.evaluation.resultFileName = "results_accoupled.mat";
    end

    cfg.evaluation.simYears = cfg.analysis.simYears;
    cfg.evaluation.selectionMode = "minObjectiveCost";

    % =====================================================================
    % 14) OUTPUT METRICS
    % =====================================================================
    % Minden uzemmodban es topologiaban ugyanazt a metrikakeszletet mentjuk.
    % Nem adunk hozza kesobb mode-specifikus metrikakat.
    %
    % Ennek celja:
    %   - barmelyik uzemmod eredmenye kesobb ujraplottolhato legyen,
    %   - AC/DC/hybrid osszehasonlitas azonos oszlopnevekkel mukodjon,
    %   - ne legyen kulon "energy_only extra metric" logika.

    cfg.output = struct();

    cfg.output.scalarMetrics = local_create_scalar_metrics();
    cfg.output.summaryMetrics = local_create_summary_metrics();
    cfg.output.profileMetrics = local_create_profile_metrics();
    cfg.output.derivedMetrics = local_create_derived_metrics();
end


function metrics = local_create_scalar_metrics()

    names = { ...
        'loadEnergy_kWh', ...
        'pvEnergyAvailable_kWh', ...
        'gridImport_kWh', ...
        'gridImportNoBess_kWh', ...
        'gridToLoad_kWh', ...
        'pvToLoad_kWh', ...
        'bessToLoad_kWh', ...
        'gridToBess_kWh', ...
        'gridToBessStored_kWh', ...
        'pvToBess_kWh', ...
        'pvToBessStored_kWh', ...
        'bessCharge_kWh', ...
        'bessDischarge_kWh', ...
        'bessThroughput_kWh', ...
        'bessDischargeBeforeConversion_kWh', ...
        'gridToBessLoss_kWh', ...
        'pvToBessLoss_kWh', ...
        'bessToLoadConversionLoss_kWh', ...
        'centralInverterLoss_kWh', ...
        'centralInvDcToAcLoss_kWh', ...
        'centralInvAcToDcLoss_kWh', ...
        'dcdcLoss_kWh', ...
        'dcdcChargeLoss_kWh', ...
        'dcdcDischargeLoss_kWh', ...
        'pcsbInverterLoss_kWh', ...
        'pcsbChargeLoss_kWh', ...
        'pcsbDischargeLoss_kWh', ...
        'bessInternalLoss_kWh', ...
        'bessInternalChargeLoss_kWh', ...
        'bessInternalDischargeLoss_kWh', ...
        'bessInternalLossDc_kWh', ...
        'bessInternalLossAc_kWh', ...
        'totalConverterLoss_kWh', ...
        'curtailment_kWh', ...
        'clippedEnergy_kWh', ...
        'gridToBessDc_kWh', ...
        'gridToBessAc_kWh', ...
        'pvToBessDc_kWh', ...
        'pvToBessAc_kWh', ...
        'bessDcToLoad_kWh', ...
        'bessAcToLoad_kWh', ...
        'bessChargeDc_kWh', ...
        'bessChargeAc_kWh', ...
        'bessDischargeDc_kWh', ...
        'bessDischargeAc_kWh', ...
        'gridToBessImportCost_HUF', ...
        'gridToBessStoredImportEquivCost_HUF', ...
        'bessStoredImportEquivCost_HUF', ...
        'bessDischargeBeforeConversionImportEquivCost_HUF', ...
        'bessToLoadImportEquivCost_HUF', ...
        'energyCost_HUF', ...
        'energyCostNoBess_HUF', ...
        'degradationCost_HUF', ...
        'overrunCost_HUF', ...
        'contractCost_HUF', ...
        'objectiveCost_HUF', ...
        'maxLoadPeak_kW', ...
        'maxPVPeak_kW', ...
        'maxGridImportPeak_kW', ...
        'maxGridImportNoBessPeak_kW', ...
        'maxBessChargePeak_kW', ...
        'maxBessDischargePeak_kW' ...
    };

    sources = { ...
        'P_load_kW', ...
        'P_pv_available_kW', ...
        'P_grid_import_kW', ...
        'P_grid_import_no_bess_kW', ...
        'P_grid_to_load_kW', ...
        'P_pv_to_load_kW', ...
        'P_bess_to_load_kW', ...
        'P_grid_to_bess_kW', ...
        'P_grid_to_bess_stored_kW', ...
        'P_pv_to_bess_kW', ...
        'P_pv_to_bess_stored_kW', ...
        'P_bess_charge_kW', ...
        'P_bess_discharge_kW', ...
        'P_bess_throughput_kW', ...
        'P_bess_discharge_before_conversion_kW', ...
        'P_grid_to_bess_loss_kW', ...
        'P_pv_to_bess_loss_kW', ...
        'P_bess_to_load_conversion_loss_kW', ...
        'P_loss_central_inv_kW', ...
        'P_loss_central_inv_dc_to_ac_kW', ...
        'P_loss_central_inv_ac_to_dc_kW', ...
        'P_loss_dcdc_kW', ...
        'P_loss_dcdc_charge_kW', ...
        'P_loss_dcdc_discharge_kW', ...
        'P_loss_pcsb_inv_kW', ...
        'P_loss_pcsb_charge_kW', ...
        'P_loss_pcsb_discharge_kW', ...
        'P_loss_bess_internal_kW', ...
        'P_loss_bess_internal_charge_kW', ...
        'P_loss_bess_internal_discharge_kW', ...
        'P_loss_bess_internal_dc_kW', ...
        'P_loss_bess_internal_ac_kW', ...
        'P_total_converter_loss_kW', ...
        'P_curtailment_kW', ...
        'P_curtailment_kW', ...
        'P_grid_to_bess_dc_kW', ...
        'P_grid_to_bess_ac_kW', ...
        'P_pv_to_bess_dc_kW', ...
        'P_pv_to_bess_ac_kW', ...
        'P_bess_dc_to_load_kW', ...
        'P_bess_ac_to_load_kW', ...
        'P_bess_charge_dc_kW', ...
        'P_bess_charge_ac_kW', ...
        'P_bess_discharge_dc_kW', ...
        'P_bess_discharge_ac_kW', ...
        'C_grid_to_bess_import_HUF', ...
        'C_grid_to_bess_stored_import_equiv_HUF', ...
        'C_bess_stored_import_equiv_HUF', ...
        'C_bess_discharge_before_conversion_import_equiv_HUF', ...
        'C_bess_to_load_import_equiv_HUF', ...
        'C_energy_step_HUF', ...
        'C_energy_no_bess_step_HUF', ...
        'C_degradation_step_HUF', ...
        'C_overrun_step_HUF', ...
        'C_contract_step_HUF', ...
        'C_objective_step_HUF', ...
        'P_load_kW', ...
        'P_pv_available_kW', ...
        'P_grid_import_kW', ...
        'P_grid_import_no_bess_kW', ...
        'P_bess_charge_kW', ...
        'P_bess_discharge_kW' ...
    };

    modes = { ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'energySum', ...
        'sum', ...
        'sum', ...
        'sum', ...
        'sum', ...
        'sum', ...
        'sum', ...
        'sum', ...
        'sum', ...
        'sum', ...
        'sum', ...
        'sum', ...
        'max', ...
        'max', ...
        'max', ...
        'max', ...
        'max', ...
        'max' ...
    };

    local_validate_metric_arrays(names, sources, modes, 'scalarMetrics');

    metrics = struct( ...
        'name', names, ...
        'source', sources, ...
        'mode', modes);
end


function metrics = local_create_summary_metrics()

    names = { ...
        'bestContract_kW', ...
        'finalSoC', ...
        'finalSoH', ...
        'finalSoH_pct', ...
        'finalSoCDc', ...
        'finalSoCAc', ...
        'finalSoHDc', ...
        'finalSoHAc', ...
        'contractSearchRuntime_s', ...
        'fullHorizonRuntime_s' ...
    };

    sources = { ...
        'bestContract_kW', ...
        'finalSoC', ...
        'finalSoH', ...
        'finalSoH_pct', ...
        'finalSoCDc', ...
        'finalSoCAc', ...
        'finalSoHDc', ...
        'finalSoHAc', ...
        'contractSearchRuntime_s', ...
        'fullHorizonRuntime_s' ...
    };

    if numel(names) ~= numel(sources)
        error('summaryMetrics name/source length mismatch.');
    end

    metrics = struct( ...
        'name', names, ...
        'source', sources);
end


function metrics = local_create_profile_metrics()

    names = { ...
        'meanLoad_kW', ...
        'peakLoad_kW', ...
        'meanPvAvailable_kW', ...
        'peakPvAvailable_kW', ...
        'meanGridImport_kW', ...
        'peakGridImport_kW', ...
        'meanGridImportNoBess_kW', ...
        'peakGridImportNoBess_kW', ...
        'meanBessCharge_kW', ...
        'peakBessCharge_kW', ...
        'meanBessDischarge_kW', ...
        'peakBessDischarge_kW', ...
        'meanCurtailment_kW', ...
        'peakCurtailment_kW', ...
        'meanSoC', ...
        'minSoC', ...
        'maxSoC' ...
    };

    sources = { ...
        'P_load_kW', ...
        'P_load_kW', ...
        'P_pv_available_kW', ...
        'P_pv_available_kW', ...
        'P_grid_import_kW', ...
        'P_grid_import_kW', ...
        'P_grid_import_no_bess_kW', ...
        'P_grid_import_no_bess_kW', ...
        'P_bess_charge_kW', ...
        'P_bess_charge_kW', ...
        'P_bess_discharge_kW', ...
        'P_bess_discharge_kW', ...
        'P_curtailment_kW', ...
        'P_curtailment_kW', ...
        'SoC', ...
        'SoC', ...
        'SoC' ...
    };

    modes = { ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'maxProfile', ...
        'meanProfile', ...
        'minProfile', ...
        'maxProfile' ...
    };

    local_validate_metric_arrays(names, sources, modes, 'profileMetrics');

    metrics = struct( ...
        'name', names, ...
        'source', sources, ...
        'mode', modes);
end


function metrics = local_create_derived_metrics()

    metrics = struct( ...
        'name', { ...
            'gridImportReduction_kWh', ...
            'gridImportReduction_pct', ...
            'peakReduction_kW', ...
            'peakReduction_pct', ...
            'energyCostSaving_HUF', ...
            'equivalentCycles', ...
            'specificObjectiveCost_HUF_per_kWhLoad', ...
            'gridToBessChargeEfficiency_pct', ...
            'pvToBessChargeEfficiency_pct', ...
            'bessDischargeToLoadEfficiency_pct', ...
            'gridToBessToLoadEfficiency_pct', ...
            'pvToBessToLoadEfficiency_pct' ...
        }, ...
        'operation', { ...
            'difference', ...
            'percentReduction', ...
            'difference', ...
            'percentReduction', ...
            'difference', ...
            'equivalentCycles', ...
            'ratio', ...
            'ratioPercent', ...
            'ratioPercent', ...
            'ratioPercent', ...
            'productPercent', ...
            'productPercent' ...
        }, ...
        'inputs', { ...
            {'gridImportNoBess_kWh', 'gridImport_kWh'}, ...
            {'gridImportNoBess_kWh', 'gridImport_kWh'}, ...
            {'maxGridImportNoBessPeak_kW', 'maxGridImportPeak_kW'}, ...
            {'maxGridImportNoBessPeak_kW', 'maxGridImportPeak_kW'}, ...
            {'energyCostNoBess_HUF', 'energyCost_HUF'}, ...
            {'bessThroughput_kWh', 'E_BESS_kWh'}, ...
            {'objectiveCost_HUF', 'loadEnergy_kWh'}, ...
            {'gridToBessStored_kWh', 'gridToBess_kWh'}, ...
            {'pvToBessStored_kWh', 'pvToBess_kWh'}, ...
            {'bessToLoad_kWh', 'bessDischargeBeforeConversion_kWh'}, ...
            {'gridToBessChargeEfficiency_pct', 'bessDischargeToLoadEfficiency_pct'}, ...
            {'pvToBessChargeEfficiency_pct', 'bessDischargeToLoadEfficiency_pct'} ...
        });
end


function local_validate_metric_arrays(names, sources, modes, label)

    if numel(names) ~= numel(sources) || numel(names) ~= numel(modes)
        error('%s definition length mismatch: names=%d, sources=%d, modes=%d.', ...
            label, numel(names), numel(sources), numel(modes));
    end

    nameStrings = string(names(:));

    if numel(unique(nameStrings)) ~= numel(nameStrings)
        error('%s contains duplicate metric names.', label);
    end
end
