function plan = ems_day_ahead_planner_milp_energy_ac( ...
    P_load_f, ...
    P_pv_dc_f, ...
    Prices, ...
    pars, ...
    tariff, ...
    dt_h, ...
    contract_state, ...
    target_step_min, ...
    dispatch_cfg)
% EMS_DAY_AHEAD_PLANNER_MILP_ENERGY_AC
%
% AC-csatolt energy-only planner.
%
% Cel:
%   - onfogyasztas noveles,
%   - energiaar-arbitrazs,
%   - nincs peak shaving cel,
%   - nincs aktiv lekotott teljesitmeny korlat.
%
% Megvalositas:
%   - contract limit nagyon magas,
%   - safety factor = 1,
%   - overrun buntetes = 0,
%   - energiaar es degradacio aktiv marad,
%   - force_hard_grid_cap = false.

    if nargin < 9 || isempty(dispatch_cfg)
        error('dispatch_cfg is required for energy-only AC planner.');
    end

    useFast = false;

    if isfield(dispatch_cfg, 'useFastDayAheadMILP')
        useFast = logical(dispatch_cfg.useFastDayAheadMILP);
    end

    contract_state_energy = contract_state;

    contract_state_energy.P_contract_kW = dispatch_cfg.energyOnlyGridCap_kW;
    contract_state_energy.P_grid_hard_cap_kW = dispatch_cfg.energyOnlyGridCap_kW;
    contract_state_energy.P_contract_safety_factor = 1.0;
    contract_state_energy.P_month_max_so_far_kW = 0;

    tariff_energy = tariff;

    tariff_energy.penalty_rate_huf_per_kW_year = 0.0;
    tariff_energy.within_contract_peak_weight_huf_per_kW_month = 0.0;

    pars_energy = pars;
    pars_energy.force_hard_grid_cap = false;

    if useFast
        plan = ems_day_ahead_planner_milp_contract_fast_ac( ...
            P_load_f, ...
            P_pv_dc_f, ...
            Prices, ...
            pars_energy, ...
            tariff_energy, ...
            dt_h, ...
            contract_state_energy, ...
            target_step_min);
    else
        plan = ems_day_ahead_planner_milp_contract_ac( ...
            P_load_f, ...
            P_pv_dc_f, ...
            Prices, ...
            pars_energy, ...
            tariff_energy, ...
            dt_h, ...
            contract_state_energy, ...
            target_step_min);
    end

    plan.objective_mode = "energy_only";
    plan.coupling = "ac";
end