function plan = ems_day_ahead_planner_milp_peak_ac( ...
    P_load_f, ...
    P_pv_dc_f, ...
    Prices, ...
    pars, ...
    tariff, ...
    dt_h, ...
    contract_state, ...
    target_step_min, ...
    dispatch_cfg)
% EMS_DAY_AHEAD_PLANNER_MILP_PEAK_AC
%
% AC-csatolt peak-only planner.
%
% Cel:
%   - BESS csak a lekotott teljesitmeny / grid peak limit tartasara dolgozzon,
%   - energiaar-arbitrazs ne legyen,
%   - onfogyasztas noveles ne legyen kulon cel,
%   - AC esetben a soft Pover valtozo legyen tiltva.

    if nargin < 9 || isempty(dispatch_cfg)
        dispatch_cfg = struct();
    end

    useFast = false;

    if isfield(dispatch_cfg, 'useFastDayAheadMILP')
        useFast = logical(dispatch_cfg.useFastDayAheadMILP);
    end

    Prices_peak = Prices;
    Prices_peak.buy_huf = zeros(size(Prices.buy_huf));

    tariff_peak = tariff;

    tariff_peak.distribution_energy_rate_huf_per_kWh = 0.0;
    tariff_peak.transmission_energy_rate_huf_per_kWh = 0.0;

    tariff_peak.curtailment_penalty_huf_per_kWh = 0.0;
    tariff_peak.noncheap_charge_penalty_huf_per_kWh = 0.0;
    tariff_peak.within_contract_peak_weight_huf_per_kW_month = 0.0;

    pars_peak = pars;
    pars_peak.force_hard_grid_cap = true;

    if useFast
        plan = ems_day_ahead_planner_milp_contract_fast_ac( ...
            P_load_f, ...
            P_pv_dc_f, ...
            Prices_peak, ...
            pars_peak, ...
            tariff_peak, ...
            dt_h, ...
            contract_state, ...
            target_step_min);
    else
        plan = ems_day_ahead_planner_milp_contract_ac( ...
            P_load_f, ...
            P_pv_dc_f, ...
            Prices_peak, ...
            pars_peak, ...
            tariff_peak, ...
            dt_h, ...
            contract_state, ...
            target_step_min);
    end

    plan.objective_mode = "peak_only";
    plan.coupling = "ac";
end