function plan = ems_day_ahead_planner_milp_energy_dc( ...
    P_load_f, ...
    P_pv_dc_f, ...
    Prices, ...
    pars, ...
    tariff, ...
    dt_h, ...
    contract_state, ...
    target_step_min, ...
    dispatch_cfg)
% EMS_DAY_AHEAD_PLANNER_MILP_ENERGY_DC
%
% DC-csatolt energy-only planner.
%
% Cel:
%   - onfogyasztas noveles,
%   - energiaar-arbitrazs,
%   - nincs peak shaving cel,
%   - nincs aktiv lekotott teljesitmeny korlat.
%
% Megvalositas:
%   - a contract limitet nagyon magasra allitjuk,
%   - a safety factort 1-re allitjuk,
%   - az overrun/contract jellegu bunteteseket nullazzuk,
%   - az energiaar es a degradacio aktiv marad.

    contract_state_energy = contract_state;

    contract_state_energy.P_contract_kW = dispatch_cfg.energyOnlyGridCap_kW;
    contract_state_energy.P_grid_hard_cap_kW = dispatch_cfg.energyOnlyGridCap_kW;
    contract_state_energy.P_contract_safety_factor = 1.0;
    contract_state_energy.P_month_max_so_far_kW = 0;

    tariff_energy = tariff;

    tariff_energy.penalty_rate_huf_per_kW_year = 0.0;
    tariff_energy.within_contract_peak_weight_huf_per_kW_month = 0.0;

    plan = ems_day_ahead_planner_milp_contract( ...
        P_load_f, ...
        P_pv_dc_f, ...
        Prices, ...
        pars, ...
        tariff_energy, ...
        dt_h, ...
        contract_state_energy, ...
        target_step_min);

    plan.objective_mode = "energy_only";
    plan.coupling = "dc";
end