function plan = ems_day_ahead_planner_milp_peak_dc( ...
    P_load_f, ...
    P_pv_dc_f, ...
    Prices, ...
    pars, ...
    tariff, ...
    dt_h, ...
    contract_state, ...
    target_step_min)
% EMS_DAY_AHEAD_PLANNER_MILP_PEAK_DC
%
% DC-csatolt peak-only planner.
%
% Cel:
%   - BESS csak a lekotott teljesitmeny / grid peak limit tartasara dolgozzon,
%   - ne legyen energiaar-arbitrazs,
%   - ne legyen onfogyasztas novelesi osztonzes,
%   - a degradacios koltseg maradjon aktiv, hogy feleslegesen ne ciklizaljon.
%
% Megvalositas:
%   - a villamosenergia arat nullazzuk,
%   - a rendszerhasznalati energia dijakat nullazzuk,
%   - a curtailment penalty-t nullazzuk,
%   - a contract hard cap valtozatlanul aktiv marad.

    Prices_peak = Prices;
    Prices_peak.buy_huf = zeros(size(Prices.buy_huf));

    tariff_peak = tariff;

    tariff_peak.distribution_energy_rate_huf_per_kWh = 0.0;
    tariff_peak.transmission_energy_rate_huf_per_kWh = 0.0;

    tariff_peak.curtailment_penalty_huf_per_kWh = 0.0;
    tariff_peak.noncheap_charge_penalty_huf_per_kWh = 0.0;
    tariff_peak.within_contract_peak_weight_huf_per_kW_month = 0.0;

    plan = ems_day_ahead_planner_milp_contract( ...
        P_load_f, ...
        P_pv_dc_f, ...
        Prices_peak, ...
        pars, ...
        tariff_peak, ...
        dt_h, ...
        contract_state, ...
        target_step_min);

    plan.objective_mode = "peak_only";
    plan.coupling = "dc";
end